version: "3.8"

services:
  redis:
    container_name: aqua.ghpvc.redis
    image: redis:latest

    restart: always

    volumes:
      - data-ghpvc-redis:/data

  api:
    build:
      context: .
      target: production
      dockerfile: Dockerfile

    container_name: aqua.ghpvc.api
    restart: always
    ports:
      - ${API_LISTEN:-8080}:8080

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  data-ghpvc-redis: {}
